---
scenario:
  name: fedora-26
platforms:
  - name: fedora-26
    groups:
      - consul_instances
    image: dokken/fedora-26
    command: /usr/lib/systemd/systemd
    capabilities:
      - SYS_ADMIN
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
