---
scenario:
  name: oraclelinux-7
platforms:
  - name: oraclelinux-7
    groups:
      - consul_instances
    image: dokken/oraclelinux-7
    command: /usr/lib/systemd/systemd
    capabilities:
      - SYS_ADMIN
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
