---
scenario:
  name: debian-9
platforms:
  - name: debian-9
    groups:
      - consul_instances
    image: dokken/debian-9
    command: /lib/systemd/systemd
    capabilities:
      - SYS_ADMIN
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
